DOMAIN = "doordrop"

CONF_IMAP_HOST = "imap_host"
CONF_IMAP_PORT = "imap_port"
CONF_IMAP_USERNAME = "imap_username"
CONF_IMAP_PASSWORD = "imap_password"
CONF_DB_HOST = "db_host"
CONF_DB_PORT = "db_port"
CONF_DB_USERNAME = "db_username"
CONF_DB_PASSWORD = "db_password"
CONF_DB_NAME = "db_name"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_MQTT_TOPIC = "mqtt_topic"
CONF_MQTT_STATUS_TOPIC = "mqtt_status_topic"
CONF_BTN_ENTITY_ID = "btn_entity_id"
CONF_AUTHORIZED_BARCODES = "authorized_barcodes"
